debug: false
management.endpoints.web.exposure.include: "*"


logging:
  level:
    com.fastcampus.board_project: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: thisis1TEST!
    driver-class-name: com.mysql.cj.jdbc.Driver
    # spring uses jpa as a bridge to make hibernate connection which is much smoother - check required
    #h2랑 연결하기 위한 임시방편
#    url : jdbc:h2:mem:testdb
#    username : sa
#    driver-class-name : org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
#  h2.console.enabled: true
  sql.init.mode: always
  # thymeleaf.cache: false
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated
#---
# 내가 설정한 테스트 디비로 테스트 진행하도록 전역 설정
#  spring:
#    config.activate.on-profile: testdb
#    datasource:
#      url: jdbc:h2:mem:board;mode=mysql
#      driverClassName: org.h2.Driver
#    sql.init.mode: always
